# Header
menu:
  归档: /archives
  订阅: /atom.xml


# Content
title: 'Title'
excerpt_link: 全文...
fancybox: false
date_format: ' YYYY 年 MM 月 DD 日'

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

#主题方案
highlight_theme: atom light

# widget behavior
archive_type: 'monthly'
show_count: false

disqus_shortname:

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: favicon.ico
avatar: avatar.png
